# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <read_individual_reos_table>
  # <read_individual_reos_table>
  "disaggregation",
  # <read_individual_reos_table>
  # <read_individual_reos_table>
  "frequency",
  # <read_individual_reos_table>
  # <read_individual_reos_table>
  "series",
  # <read_individual_reos_table>
  # <read_individual_reos_table>
  "topic",
  # <read_individual_reos_table>
  # <read_individual_reos_table>
  "value",
  NULL
))
